[project]
name = 'Academic-Integrity-Blockchain'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.degree-authenticity-registry]
path = 'contracts/degree-authenticity-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.employer-verification-portal]
path = 'contracts/employer-verification-portal.clar'
clarity_version = 3
epoch = '3.2'

[contracts.lifelong-learning-rewards]
path = 'contracts/lifelong-learning-rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.skill-assessment-validator]
path = 'contracts/skill-assessment-validator.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
